version: '3.8'
# hello world 3
services:
  # Banco
  db:
    container_name: denuncias-banco
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # PHP e dependencias
  app:
    container_name: denuncias-app
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www
    working_dir: /var/www
    depends_on:
      - db

  # Servidor web
  nginx:
    container_name: denuncias-webserver
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data:
